spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3300/auth_banco_dev}
   # url: ${DB_URL:jdbc:mysql://localhost:3300/auth_banco_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
